### ISSUE TITLE
Domain already in use

### ISSUE THREAD

**Issue by sl4cky** [Ice3man543/SubOver#10]
Hi, 
Your tool gave me this output: Takeover Possible At : <DOMAIN> 

This is the dig output: 
DiG 9.11.3-1ubuntu1-Ubuntu <<>> CNAME unbouncepages.com
it determined that out of this output the domain is vulnerable to subdomain takeover, 
when registering to unbouncepages.com to try to claim the original domain it says that the domain is already in use.

![peakon](https://user-images.githubusercontent.com/13188087/40159651-f76380c4-59b2-11e8-9638-2b6845d20c21.png)

**Comment by Ice3man543** [comment]
Hi, 
This is not a problem of SubOver. Actually, it's an issue with the provider itself. Maybe they have fixed the flaw. I'll check and get back to you.

**Comment by Ice3man543** [comment]
Closing this since it's a problem of provider and not the tool itself :+1:
