### ISSUE TITLE
Wrong fmt.Print function

### ISSUE THREAD

**Issue by eur0pa** [Ice3man543/SubOver#11]
https://github.com/Ice3man543/SubOver/blob/7d7ca40932376f8575ffd9bba88da358581d0c51/subover.go#L166

Either use:

`fmt.Printf("\n[\033[31;1;4mCLOUDFRONT\033[0m] Takeover Possible At : %s With HTTP & HTTPS\n", s.Url)`

or

`fmt.Println("\n[\033[31;1;4mCLOUDFRONT\033[0m] Takeover Possible At : " + s.Url + " With HTTP & HTTPS")`

**Comment by Ice3man543** [comment]
Yeah @eur0pa, i knew about that error. Forgot to fix it. I am going to rewrite the tool anyway. :+1:
Thanks for notifying.

**Comment by butterskinny** [comment]
bro, github subdomain not detected by scanner?
thank you for this awesome project

**Comment by Ice3man543** [comment]
Hey @butterskinny, thanks for the compliment. Afaik, github pages is detetcted by the tool!

**Comment by butterskinny** [comment]
@Ice3man543 So far , no github subdomain detected by subover.
I try so hard with a some test . fastly,surge,tumblr working fine.

**Comment by butterskinny** [comment]
I got this error message https://pastebin.com/DJc45dxg @Ice3man543 .

**Comment by Ice3man543** [comment]
@butterskinny It's probably a problem with the way subdomains are setup on Github Pages. I have myself found Github Pages takeovers using this tool. It seems to work fine,
