### ISSUE TITLE
Error message: open /src/github.com/Ice3man543/SubOver/providers.json: no such file or directory

### ISSUE THREAD

**Issue by kohldampfer** [Ice3man543/SubOver#13]
I did what is written in the documentation: 

` go get github.com/Ice3man543/SubOver`

Now, I find a new file `~/go/bin/SubOver` in my personal home directory. When I now call `~/go/bin/SubOver`, I get this message

```
$ ~/go/bin/SubOver -l output.temp 

SubOver v.1.2              Nizamul Rana (@Ice3man)
==================================================

open /src/github.com/Ice3man543/SubOver/providers.json: no such file or directory

```

**Edit**

I've done this on an Ubuntu 18.04 machine.

**Comment by Ice3man543** [comment]
What is your gopath?

**Comment by ehsandeep** [comment]
@kohldampfer 

Update your `.profile` and add following lines and it should work. 

```
nano ~/.profile
```
Paste below lines. 

```
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
source ~/.profile
```

**Comment by ghsec** [comment]
I have the same problem, I edit and add in gopath
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

but problem is not fixed

**Comment by TruthD** [comment]
Same problem here

**Comment by zevlag** [comment]
I got it to work by doing this:
`cd ~/go/src/github.com/Ice3man543/SubOver`

**Comment by apertureless** [comment]
I've got the same issue.

I think it has to do with

```go
raw, err := ioutil.ReadFile("providers.json")
```


If you have the `$GOPATH` in your path variable, you can run SubOver from anywhere.

However if you run it, it will reference `/Users/username/$GOPATH/bin/SubOver`
But in the `bin` folder are only the executeables, thus `providers.json` can not be found. 

However symlinking the `providers.json` does not work either.

The only workaround I found so far is to run it from the `src/` folder with `go run subover.go`

**Comment by Ice3man543** [comment]
Sorry for the late response, actually the public project is discontinued. Please check https://github.com/haccer/subjack. I am not maintaining this at the moment.

**Comment by SlavicaCaca** [comment]
I had the same issue and this solved my problem:
When specifying list of hosts instead writing it like this SubOver -l ./subdomains.txt if it's in root folder write it like this SubOver -l $HOME/subdomains.txt
