### ISSUE TITLE
looks like the tool does not do anything

### ISSUE THREAD

**Issue by rhalyc** [Ice3man543/SubOver#14]
Hello,
When I execute this tool this is the output that I get:
`Sub0ver -v -l domains.txt`
![screen shot 2018-06-24 at 22 48 58](https://user-images.githubusercontent.com/32094066/41823493-158e0558-7801-11e8-88a6-98ad99f50df0.png)

It looks like the tool isn't working.
The content of the file domains.txt is a list of domains, for example:
www.example.com
new.domain.com
other.domain.com

**Comment by ehsandeep** [comment]
@rhalyc, 

You will any result if you sub domain is vulnerable for the subdomain takeover, otherwise this is expected output, any way you can use verbose mode to see what's happening.

**Comment by Ice3man543** [comment]
@rhalyc You can try using -v flag to enable verbosity. @madaratech Thanks for explaining. The tool will report takeovers only when it's found some.

**Comment by rhalyc** [comment]
Thank you for the responses,
In my example I used the flag "-v" but the output is the same using or not that flag. That is why I think that maybe is something not working properly?

**Comment by Ice3man543** [comment]
Try to update your version of the tool. If it doesn't work, use the -a flag to test all hosts. 
AFAIK updating the tool will fix it.

**Comment by rhalyc** [comment]
Perfect. It is working.
Thank you!
