### ISSUE TITLE
Check for www.sub.domain.com too

### ISSUE THREAD

**Issue by bugbaba** [Ice3man543/SubOver#16]
Hi,

It would be great if SubOver can also append `www.` in front of list provided and then check them to see if it gives different result.

**Reference :**  [https://www.freelists.org/post/bugbounty/Bug-bounty-tip-The-www-subdomain-takeover-trick](https://www.freelists.org/post/bugbounty/Bug-bounty-tip-The-www-subdomain-takeover-trick)

Regards,
@bugbaba

**Comment by Ice3man543** [comment]
Great idea. I will work on this in future.

**Comment by Ice3man543** [comment]
Sorry for the late response, actually the public project is discontinued. Please check https://github.com/haccer/subjack. I am not maintaining this at the moment.
