### ISSUE TITLE
Unable to find subdomain takeover for unbounce

### ISSUE THREAD

**Issue by ranjit-git** [Ice3man543/SubOver#17]
create your wordlist with studio.wrike.com
this domain is takeover possible but your tool is unable to detect it.

**Comment by Ice3man543** [comment]
Can you provide more detail?

**Comment by Damian89** [comment]
Hi,
its because the http header has to be checked and not the response itself (noticed it some time ago). The markers you are using are correct (Page does not exists, ...) but it looks like you are checking the http_body only, but in this case also the http header has to be checked.

**Comment by Ice3man543** [comment]
Thanks for the detailed response. I'll fix this really soon, I promise.

**Comment by Damian89** [comment]
You are welcome!

Another example is: explore.luxuryretreats.com

But: studio.wrike.com and explore.luxuryretreats.com are not vulnerable (since unbounce is a special case, we have to check if its really possible to register those subdomains @ unbounce). In both cases thats not the case!

**Comment by Ice3man543** [comment]
Yeah, I have read that ubvounce only allows takeover when the domain wasn't added even once to a service. Else not.

**Comment by Ice3man543** [comment]
Sorry for the late response, actually the public project is discontinued. Please check https://github.com/haccer/subjack. I am not maintaining this at the moment.
