### ISSUE TITLE
Github page takeover doesn't work

### ISSUE THREAD

**Issue by swisskyrepo** [Ice3man543/SubOver#18]
You might need to update the providers.json to detect the Github Page TakeOver at
https://github.com/Ice3man543/SubOver/blob/0d5eed6da6bf525eb7d4b3658a1d8af96842b1b0/providers.json#L4

For my case the DNS for the takeover looked like 
`github.github.io.	1412	IN	CNAME	sni.github.map.fastly.net.`

What do you think about updating it to match the following ?
`"cname":["github.io", "fastly.net", "github.com", "github.map"], `

Cheers

**Comment by Ice3man543** [comment]
Thanks for notifying. I think the new structure makes sense. I'll update it as soon as I get on a computer :)

**Comment by swisskyrepo** [comment]
Fixed in your last commit https://github.com/Ice3man543/SubOver/commit/13f3fedec37a166e0c7e3199b7818fc9c064a61c
Thx :D
