### ISSUE TITLE
Detect Azure's traffic manager subdomains (trafficmanager.net)

### ISSUE THREAD

**Issue by menzow** [Ice3man543/SubOver#19]
Traffic Manager lets you route traffic within Azure. Using cnames to xxx.trafficmanager.net it's sometimes possible to takeover such routing. Portal link: https://portal.azure.com/#create/Microsoft.WebSite

More info: https://azure.microsoft.com/en-us/services/traffic-manager/

<img width="860" alt="screen shot 2018-07-26" src="https://user-images.githubusercontent.com/5744434/43285207-861fc2da-911e-11e8-84e9-56e98dba948b.png">

**Comment by AliSalman-et-al** [comment]
In addition to Traffic Manager profiles Cloud Services (*.cloudapp.net) and Blob Storages (*.blob.core.windows.net) are also vulnerable to Subdomain Takeovers. Which are not detected by SubOver.

**Comment by Ice3man543** [comment]
Sorry for the late response, actually the public project is discontinued. Please check https://github.com/haccer/subjack. I am not maintaining this at the moment.
