### ISSUE TITLE
argument -o is useless

### ISSUE THREAD

**Issue by s0llar** [Ice3man543/SubOver#20]
-o is useless coz results output only on screen and never to file. Please fix this

**Comment by ehsandeep** [comment]
Check > https://github.com/subfinder/subfinder

**Comment by s0llar** [comment]
And?

**Comment by Ice3man543** [comment]
Sorry for the late response, actually the public project is discontinued. Please check https://github.com/haccer/subjack. I am not maintaining this at the moment.

**Comment by s0llar** [comment]
Thanks
