### ISSUE TITLE
Differences from tko-subs?

### ISSUE THREAD

**Issue by 0xdevalias** [Ice3man543/SubOver#3]
Heya,

Curious what improvements/differences this has over https://github.com/anshumanbh/tko-subs and/or other existing tools to warrant the 'most powerful' label.

Always curious about new tools and how they can improve my efficiency :3

**Comment by Ice3man543** [comment]
Well, first big difference is that it has more providers. While tko-subs has 30 providers, subover uses 35. Next big difference comes in terms of data storage format. I am a huge fan of Json format, and it's also the most versatile format. Therefore, I used Json format for creating data file hence it could be used by anyone due it's simplicity. 

Another big improvement is in terms of responses. Sometimes, sites may respond differently, therefore we use multiple responses. 

Colours and aesthetics are better. We try no automatic subdomain takeover and leave the user to do it manually. 

All in all, tko-subs is a great tool and was an inspiration for this tool. 
Thanks

**Comment by 0xdevalias** [comment]
Fair enough. So a few tech choice differences, and some aesthetics/UX. The multiple responses aspect could be useful, didn't realise the providers had different responses.

Thanks for the info :)

**Comment by Ice3man543** [comment]
Also, in terms of speed, it is pretty damn fast. I was able to resolve a list of 315 subdomains in just 15 seconds with a slow internet connection. :3

**Comment by Ice3man543** [comment]
If you have any ideas for improvement, they would be very welcomed.
