### ISSUE TITLE
Automatically check both HTTP and HTTPS for Cloudfront 

### ISSUE THREAD

**Issue by sa7mon** [Ice3man543/SubOver#6]
First off, love the tool. Great work.

Since Cloudfront domains can be either HTTP or HTTPS, can you add functionality to also check whichever protocol wasn't supplied? Maybe this could be a boolean argument like `--check-protocols` or something.

I'd fork and add it, but I haven't learned Go yet.

Thanks!

**Comment by Ice3man543** [comment]
Hey sa7mon, I am happy that you liked the tool. I was actualy added that functionality yesterday but haven't committed it yet. Will push the changes today. Thanks.

**Comment by Ice3man543** [comment]
Sorry, a minor typo. I had actually added that yesterday.

**Comment by Ice3man543** [comment]
Done. Thanks @sa7mon
